const InteractionsActionTypes = {
    FETCH_INTERACTIONS_START: 'FETCH_INTERACTIONS_START',
    FETCH_INTERACTIONS_SUCCESS: 'FETCH_INTERACTIONS_SUCCESS',
    FETCH_INTERACTIONS_FAILURE: 'FETCH_INTERACTIONS_FAILURE',
    ADD_INTERACTION: 'ADD_INTERACTION',
}

export default InteractionsActionTypes;