const InteractionsActionTypes = {
    FETCH_INTERACTIONS_START: 'FETCH_INTERACTIONS_START',
    FETCH_INTERACTIONS_SUCCESS: 'FETCH_INTERACTIONS_SUCCESS',
    FETCH_INTERACTIONS_FAILURE: 'FETCH_INTERACTIONS_FAILURE',
    ADD_INTERACTION: 'ADD_INTERACTION',
    SELECT_INTERACTION: 'SELECT_INTERACTION',
    REMOVE_SELECTED_INTERACTION: 'REMOVE_SELECTED_INTERACTION',
    UPDATE_INTERACTION: 'UPDATE_INTERACTION',
    RESET_INTERACTIONS: 'RESET_INTERACTIONS'
}

export default InteractionsActionTypes;