const JobActionTypes = {
    FETCH_JOBS_START: 'FETCH_JOBS_START',
    FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
    FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE',
    ADD_JOB: 'ADD_JOB',
    SELECT_JOB: 'SELECT_JOB',
    SHOW_MODAL: 'SHOW_MODAL',
    UPDATE_JOB: 'UPDATE_JOB',
}

export default JobActionTypes;